url: 'http://127.0.0.1:8082' #"http://node-meter.apps.eu.cfdev.canopy-cloud.com" # 

mongodb:
  server:   "127.0.0.1" #"10.0.12.32" #
  database: uptime #"c5aa96f7-0916-4308-b1b5-e48905c2a1e8" #
  user:     root # "7d89f662-3800-4ed8-a7b4-cae589abdc43" #
  password: root #"d16d7785bc8cc26959162f23e7a14c20"
  connectionString: "mongodb://localhost:27017/uptime"      # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://127.0.0.1:8082/api' #"http://node-meter.apps.eu.cfdev.canopy-cloud.com/api" # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  # - ./plugins/email
  # - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:            
      user:          # The email account username, e.g. 'username@gmail.com'
      pass:          # The email account password, e.G. 'password'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from:            # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
    to:              # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

basicAuth:
  username:    admin
  password:    password
verbose: true # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions: 
